site_name: SlicerDiffusionComplexityMap
repo_url: https://github.com/CSIM-Toolkits/SlicerDiffusionComplexityMap
repo_name: LOAMRI/Slicer-ASLtoolkit
edit_uri: tree/main/docs

theme:
  name: readthedocs
  language: en
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - footnotes

nav:
  - 'index.md'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [SlicerDiffusionComplexityMap]